# Generated by Django 2.2.6 on 2019-11-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indextypegoodsbanner',
            name='index',
            field=models.SmallIntegerField(default=0, verbose_name='展示顺序'),
        ),
        migrations.AlterField(
            model_name='indexpromotionbanner',
            name='url',
            field=models.CharField(max_length=256, verbose_name='活动链接'),
        ),
    ]
